name: lava_snn_ripples
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.9
  - pip
  - pip:
    - h5py=3.11.0
    - keras=2.15.0
    - tensorflow=2.15.0
    - torch=2.0.0
    - torchvision=0.15.1
    - lava=0.4.1
    - lava-dl=0.5.0
    - lava-ncs=0.9.0
    - matplotlib=3.9.0
    - numpy=1.26.4
    - pandas=2.2.2
    - scikit-learn=1.5.0
    - scipy=1.13.1